### PR TITLE
Update Candid Files

### PR DESCRIPTION
**Pull request by sa-github-api**
# Motivation
The canisters APIs have been updated.

# Changes
* Updated the candid interface files for the canisters used in this library.
* Updated the javascript bindings for the latest candid interfaces.

# Tests
  - [ ] Please check the API updates for any breaking changes that affect our code.

### CODE REVIEW

**Comment by peterpeterparker** [comment]
Add `log_visibility: { controllers: null }` to mock data for ic-mgmt.

**Comment by peterpeterparker** [comment]
Ultimately I provided a PR #638 incorporate first the `log_visibility`.

**Comment by dskloetd** [comment]
Thanks. Shall we close this? Can we kick off another automatic PR or are you fixing other related things as well? (I didn't check if anything else needs fixing.)

**Comment by peterpeterparker** [comment]
Sure we can close it and kick off another automatic PR later. There are other changes to inherit, notably the new ICRC-21 and 10 standards in both ledgers.

**Pull request closed without merging**
