### PR TITLE
build: open next version

### PR DESCRIPTION
**Pull request by peterpeterparker**
# Motivation

[v0.15.0](https://github.com/dfinity/ic-js/releases/tag/v0.15.0) has just been released. This bump version numbers to open next version.

### CODE REVIEW

**Review by lmuntaner — APPROVED** [review]
Thanks!

**Comment by lmuntaner** [comment]
Can you add this task to the ADMIN readme of publishing a new version?

**Comment by peterpeterparker** [comment]
@lmuntaner not sure what to comment, pretty standard that you have to bump the version number if you want to release a new version. which step is particularly unclear?

**Comment by peterpeterparker** [comment]
Note added in [ADMIN](./ADMIN.md).

**Pull request merged**
