### PR TITLE
GIX-1960: Upgrade candid sns-js

### PR DESCRIPTION
**Pull request by lmuntaner**
# Motivation

Support latest fields for Neurons' Fund enhancements.

In this PR, upgrade candid for sns-js

# Changes

## Automatic changes

* `.did` files with `./scripts/import-candid`.
* Types and idl files related to candid: `./scripts/compile-idl-js`.

## Manual changes

* Reverted changes in packages other than `sns`.
* Add field to mock data.

# Tests

Still passing.

# Todos

- [ ] Add entry to changelog (if necessary).

### CODE REVIEW

**Comment by lmuntaner** [comment]
@dskloetd please review

Already working on the nnsdapp which I'm planning to do right after.

**Review by dskloetd — APPROVED** [review]
Did you manually revert changes outside sns (if so, would be good to mention in the PR description) or were there no changes outside sns?

**Comment by lmuntaner** [comment]
> Did you manually revert changes outside sns (if so, would be good to mention in the PR description) or were there no changes outside sns?

I honestly didn't check. I reverted them; there is always the change of the commit in the comment at the top.

**Comment by dskloetd** [comment]
OK, I've added it to the PR description.

**Pull request merged**
