### PR TITLE
fix: Nns request converter "this is not a constructor"

### PR DESCRIPTION
**Pull request by peterpeterparker**
# Motivation

Fix mapping `Principal` in the Nns `request.converter`.

```
TypeError: this is not a constructor
    at fromText (chunk-GURPV5CO.js?v=adf4f374:738:23)
    at Array.map (<anonymous>)
    at Ui (@dfinity_nns.js?v=7b572303:2288:226)
    at er (@dfinity_nns.js?v=7b572303:2330:80)
    at cr (@dfinity_nns.js?v=7b572303:2433:115)
    at makeProposal (@dfinity_nns.js?v=7b572303:2753:16)
    at makeProposal (icp-proposal.api.ts:102:9)
    at async submitProposal (proposal.services.ts:108:22)
    at async submitProposal (submit.services.ts:432:34)
    at async HTMLFormElement.onSubmit (SubmitReview.svelte:45:19)
```

# Changes

- `Principal.fromText` cannot be used as a function when mapping an array

# Screenshots

Capture d’écran 2024-07-07 à 18 46 56

### CODE REVIEW

**Comment by dskloetd** [comment]
Why did this not fail on CI?

**Comment by peterpeterparker** [comment]
Probably because it is not covered by a test. I did not provided one here as I provided the fix on my spare time and was more focused on making my overall solution works out on a Sunday evening. Moreover, that's probably not the only type of makeProposal that is not covered.

**Comment by dskloetd** [comment]
@mstrasinskis can you take this over and add a test for it?

**Comment by mstrasinskis** [comment]
> @mstrasinskis can you take this over and add a test for it?

Sure.

**Comment by peterpeterparker** [comment]
Given that it was not covered by a test in the first place, can we unblock this PR and provide those additional new tests in a separate PR?

**Comment by dskloetd** [comment]
Just because we did it wrong in the first place, doesn't mean it's ok to do it wrong now.
Feel free to remove the untested and unused code but if you want to add or fix something it needs to have test.
The fact that it was broken makes it even more clear why tests are needed.
Either @mstrasinskis can add the tests when he has time or you can make sure at least the changed code is covered.

**Comment by peterpeterparker** [comment]
I have added a test. If you run it on main @dskloetd it fails for the reason resolved in this PR.

**Review by dskloetd — APPROVED** [review]
Thank you!

**Pull request merged**
