### PR TITLE
refactor: nns enums

### PR DESCRIPTION
**Pull request by peterpeterparker**
# Motivation

refactor exported enums to `enums` to make these easier to find

# Changes

Update accordingly.

### CODE REVIEW

**Review by lmuntaner — COMMENTED** [review]
Why is it in draft?

**Comment by peterpeterparker** [comment]
You can review it, just testing one more thing in nns-dapp

**Review by lmuntaner — APPROVED** [review]
LGTM, thanks!

**Comment by peterpeterparker** [comment]
PR was originally meant to introduce an enum for the NNSFunction but ultimately we are already using these indexed with a number in NNS-dapp as provided by candid. The refactoring being a goodie, we keep that part though.

**Pull request merged**
