### PR TITLE
Add --silent to `npm pack`

### PR DESCRIPTION
**Pull request by lmuntaner**
# Motivation

@frederikrothenberger discovered that the outupt of `npm pack` is different depending on the npm version.

Later versions of `npm` output some commands. Adding `--silent` ensures that the output is a valid JSON without the commands.

# Changes

* Add `--silent` to `publish-npm.sh`.

# Tests

Tested manually.

# Todos

- [ ] Add entry to changelog (if necessary). NOT necessary.

### CODE REVIEW

**Comment by lmuntaner** [comment]
@dskloetd @peterpeterparker please review

**Review by peterpeterparker — APPROVED** [review]
LGTM, thanks

**Comment by dskloetd** [comment]
Are you sure those commands aren't output on stderr instead of stdout? Not output JSON when `--json` is passed sounds like a major bug. Was it reported back to them?

**Comment by lmuntaner** [comment]
> Are you sure those commands aren't output on stderr instead of stdout? Not outputing JSON when `--json` is passed sounds like a major bug. Was it reported back to them?

We found an issuer reporting it, and they considered it as fixed with the `--silent` flag.

https://github.com/npm/cli/issues/7354

**Pull request merged**
