### PR TITLE
NNS1-2886: Remove nns-proto dependency from @dfinity/nns

### PR DESCRIPTION
**Pull request by dskloetd**
# Motivation

The NNS dapp now requires version 2.4.9 of the Internet Computer Ledger app.
See for context: https://forum.dfinity.org/t/nns-dapp-to-remove-protobuf-dependency-upgrade-your-ledger-ic-app-to-2-4-9/27712
This means that we no longer need to use a separate code path with protocol buffers when making hardware wallet transactions but can instead use the exact same code path as for normal transactions.

NNS-dapp already doesn't use hardware wallet specific code paths since https://github.com/dfinity/nns-dapp/pull/4373

# Changes

1. Remove the dependency from `@dfinity/nns` on `@dfinity/nns-proto`.
2. Remove the hardware wallet specific code paths. Hardware wallets will use the standard candid code.
3. Remove code that becomes unused as a result.

Note that there is one slight behavior change. Previously `listNeurons` would throw `FeatureNotSupportedError` if you try to call it with `certified == false` with `this.hardwareWallet == true`. Since we no longer have `this.hardwareWallet`, we can't do this anymore. The hardware wallet will now return an empty signature and it's up to the signing identity to throw an error as a response. NNS dapp does this, but also doesn't call `listNeurons` with `certified = false`.

# Tests

Hardware wallet specific tests have been removed.

# Todos

- [x] Add entry to changelog (if necessary).

### CODE REVIEW

**Review by mstrasinskis — APPROVED** [review]
Nice 👍

**Comment by peterpeterparker** [comment]
Cool 👍

That was the last PR? In next version of ic-js we should mark `nns-proto` library as deprecated (here and on npm).

**Comment by dskloetd** [comment]
This should be the last PR on ic-js. I'm going to do some manual testing on NNS dapp to make sure everything still work with the HW and then update nns-dapp.

**Comment by peterpeterparker** [comment]
Super!

**Comment by dskloetd** [comment]
Manually tested that the following still work with hardware wallet:
* transfer
* listNeurons
* increaseDissolveDelay
* startDissolving
* stopDissolving
* disburse
* spawnNeuron
* addHotkey
* removeHotkey

Do you want to deprecate the package? (or point me how to do it)

**Pull request merged**
