### PR TITLE
build: init ledger-icp library

### PR DESCRIPTION
**Pull request by peterpeterparker**
# Motivation

Init the library dedicated the the ICP ledger.

# Notes

No logic, this PR strictly provide the lib structure.

The lib has also not been integrated in the publish pipelines.

### CODE REVIEW

**Review by lmuntaner — APPROVED** [review]
Thanks!

We should just move the LedgerCanister class from nns-js, right?

**Comment by peterpeterparker** [comment]
> We should just move the LedgerCanister class from nns-js, right?

Definitely. It's just cleaner to have a first PR with just the architecture without code in my opionion, therefore this first PR.
Next one will (begin) to move stuffs around.

**Comment by peterpeterparker** [comment]
Thanks for the review

**Comment by lmuntaner** [comment]
> > We should just move the LedgerCanister class from nns-js, right?
> 
> Definitely. It's just cleaner to have a first PR with just the architecture without code in my opionion, therefore this first PR. Next one will (begin) to move stuffs around.

Totally agree!

**Pull request merged**
