### PR TITLE
Test for proposal serialization to JSON

### PR DESCRIPTION
**Pull request by bitdivine**
# Motivation
Proposals need to be pretty!

# Changes

# Tests

### CODE REVIEW

**Comment by peterpeterparker** [comment]
What's this PR?

@mstrasinskis has implemented the de-serialization of principal for nns-dapp in https://github.com/dfinity/nns-js/pull/80

**Comment by bitdivine** [comment]
@peterpeterparker - spot the missing tests in that PR. :-)

**Comment by peterpeterparker** [comment]
@bitdivine yes but shouldn't this PR finds place in `nns-dapp` as we format the principal and use the dummy-proposals.utils.js` there  already? maybe I am missing something...

**Comment by peterpeterparker** [comment]
@bitdivine thanks for the feedback. our plan is to move the format in nns-dapp so maybe this will be move there ultimately too

**Comment by peterpeterparker** [comment]
This PR can be closed. Proposals dummy script is in NNS-dapp.

**Pull request closed without merging**
