### PR TITLE
GIX-1909: Update candid files sns-js

### PR DESCRIPTION
**Pull request by lmuntaner**
# Motivation

Use the new fields for the Neurons' Fund enhancements.

In this PR, upgrade the candid files for sns canisters.

# Changes

## Automatic changes

Script `./scripts/import-candid ../ic`. It uses the local copy of the IC repo.
* Update candid files. Files with extension `.did`.

Script `./scripts/compile-idl-js`.
* Update related candid types and JS files.

## Manual changes

Only the change in `src/index.ts`
* Export new type `NeuronsFundParticipationConstraints` that has the maximum commitment of the Neurons' Fund.

# Tests

* Fixed a mock data with new parameters.

### CODE REVIEW

**Comment by lmuntaner** [comment]
@dskloetd @mstrasinskis please review

**Comment by dskloetd** [comment]
Were some or all of the changes in this PR automated by a script?
If yes, can you put the exact script invocation in the PR description?
And if there were also manual changes, can you clearly describe what was automated and what was manual?

**Comment by lmuntaner** [comment]
> Were some or all of the changes in this PR automated by a script? If yes, can you put the exact script invocation in the PR description? And if there were also manual changes, can you clearly describe what was automated and what was manual?

Done! Ready for review

**Review by dskloetd — APPROVED** [review]
Thanks!

**Pull request merged**
